name: vitallens_flutter
description: A Flutter app for real-time heart rate and respiration detection using VitalLens API.
publish_to: "none" # 本地项目不用上传到 pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  dio: ^5.7.0
  permission_handler: ^11.0.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
